name: Gentrate ASCII Artwork

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v4
        
        - name: Listing Files
          run: ls -ltra

        - name: shell script
          run: ./asccii.sh