name: Laptop Self-hosted Build

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Docker image
      run: |
        docker build -t my-app .

    - name: Run container
      run: |
        docker run -d -p 80:9090 my-app2
